#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run type-check for frontend
echo "Running TypeScript check for frontend..."
cd frontend
npm run check-build
if [ $? -ne 0 ]; then
  echo "Type-check failed in frontend. Aborting push."
  exit 1
fi

# Run type-check for backend
echo "Running TypeScript check for backend..."
cd ../backend
npm run check-build
if [ $? -ne 0 ]; then
  echo "Type-check failed in backend. Aborting push."
  exit 1
fi

echo "Type-check passed! Proceeding with push..."
